/armor_detector:
  ros__parameters:
    use_sensor_data_qos: false
    debug_mode: true

    detector:
      camera_name: 'camera'
      subscribe_compressed: false

      # Model 
      model_path: 'package://openvino_armor_detector/model/opt-1208-001.onnx'
      device_type: 'AUTO'
      confidence_threshold: 0.80
      top_k: 128
      nms_threshold: 0.3
      detect_color: 0


/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 8.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.005
    device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"


/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0
